services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/output:/app/output
    environment:
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
